name: Eternity APK Build and Sign 

on:
  schedule:
    - cron: "0 1 * * 0"
  push:
    paths: .github/workflows/eternity.yml
  workflow_dispatch:

jobs:
  tag:
    name: Build
    runs-on: ubuntu-latest
    env:
      NDK_CCACHE: ${{ github.workspace }}/ccache
    steps:
      - name: Download Eternity's source code
        run: git clone https://codeberg.org/Bazsalanszky/Eternity.git .

      - name: Install APK Signer
        run: |
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.2.1/uber-apk-signer-1.2.1.jar -O uber-apk-signer.jar
          echo "47ae984df200afbae292d6f950e517afb445d3c902a1edc7717a82c513c5e772 uber-apk-signer.jar" | sha256sum -c

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: oracle
          check-latest: true
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ./gradlew tasks --all
          ./gradlew :app:release
          find * -name *.apk
          ls -R .

      - name: Sign APK
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
          java -jar uber-apk-signer.jar --allowResign --apks app/build/outputs/apk_from_bundle/externRelease/*.apk --ks keystore.jks --ksAlias "${{ secrets.ANDROID_KEYSTORE_ALIAS }}" --ksKeyPass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --ksPass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" -o signed/

      - name: Remove Keystore
        if: always()
        run: rm -f keystore.jks
        
      - name: Upload APK
        uses: actions/upload-artifact@v4.1.0
        with:
          name: signed
          if-no-files-found: error
          path: |
            signed/

      - name: Upload the APK to Telegram
        run: curl -F document=@"signed/*.apk" https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}

