name: Mollyim build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
      with:
        repository: theoware/mollyim-android

    - name: Create staging keystore
      run: echo "$MOLLY_STAGING_KEYSTORE" | base64 -d > app/staging.keystore
      env:
        MOLLY_STAGING_KEYSTORE: ${{ secrets.MOLLY_STAGING_KEYSTORE }}

    - name: Clone bare repo
      run: git clone https://github.com/theoware/mollyim-android/ bare

    - name: Build Docker image
      run: docker-compose build
      working-directory: reproducible-builds

    - name: Build APKs
      run: docker-compose run reproducible-molly
      working-directory: reproducible-builds
      env:
        BUILD_SCAN: 1
        STAGING_KEYSTORE_PATH: staging.keystore
        STAGING_KEYSTORE_PASSWORD: ${{ secrets.MOLLY_STAGING_KEYSTORE_PASSWORD }}

    - name: Log checksums
      run: find reproducible-builds/outputs/apk -name "*.apk" -exec sha256sum '{}' \;

    - name: Upload APKs
      uses: actions/upload-artifact@v2
      with:
        name: molly-apk-docker
        path: reproducible-builds/outputs/apk/**/release/*.apk
        if-no-files-found: error

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Get the version
        id: get-version
        run: |
          git clone --bare https://github.com/theoware/mollyim-android molly
          cd molly
          echo ::set-output name=VERSION::$(git describe --tags --abbrev=0)
          rm -rf ../molly

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Molly Android ${{ steps.get-version.outputs.VERSION }}
          draft: true
          prerelease: ${{ contains(steps.get-version.outputs.VERSION, 'rc') }}

      - name: Upload APK staging
        if: contains(steps.get-version.outputs.VERSION, 'rc')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./molly-apk-docker/stagingNonFree/release/Molly-staging-release-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
          asset_name: Molly-staging-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
          asset_content_type: application/zip

      - name: Upload APK production
        if: "!contains(steps.get-version.outputs.VERSION, 'rc')"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./molly-apk-docker/prodNonFree/release/Molly-prod-release-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
          asset_name: Molly-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
          asset_content_type: application/zip

      - name: Upload APK staging FOSS
        if: contains(steps.get-version.outputs.VERSION, 'rc')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./molly-apk-docker/stagingFree/release/Molly-staging-release-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
          asset_name: Molly-staging-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
          asset_content_type: application/zip

      - name: Upload APK production FOSS
        if: "!contains(steps.get-version.outputs.VERSION, 'rc')"
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./molly-apk-docker/prodFree/release/Molly-prod-release-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
          asset_name: Molly-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
          asset_content_type: application/zip
      - name: Send fail message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ GITHUB.WORKFLOW }} succeeded
      - name: Send suceed message
        if: ${{ !failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ GITHUB.WORKFLOW }} succeeded