name: UUP dump downloader

on:
  workflow_dispatch:
    inputs:
      build:
        required: true
      lang:
        required: true
        default: de-de
      edition:
        required: true
        default: PROFESSIONAL

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        run: |
          sudo apt-get install aria2 cabextract wimtools chntpw genisoimage
          wget https://raw.githubusercontent.com/uup-dump/converter/master/convert.sh

      - name: Retrieve aria2 script
        run: |
          aria2c --no-conf --log-level=info --log="aria2_download.log" -o"aria2_script.txt" --allow-overwrite=true --auto-file-renaming=false "https://uupdump.net/get.php?id=${{ github.event.inputs.build }}&pack=${{ github.event.inputs.lang }}&edition=${{ github.event.inputs.edition }}&aria2=2"

      - name: Download files
        run: |
          aria2c --no-conf --log-level=info --log="aria2_download.log" -x16 -s16 -j5 -c -R -d"." -i"aria2_script.txt"

      - name: Convert
        run: |
          chmod +x ./convert.sh
          ./convert.sh wim "." 0

      - name: Get file name
        id: iso
        run: |
          echo "::set-output name=name::$(find * -name *.ISO -type f)"

      - name: Split files
        run: |
          split --bytes=2147483647 --numeric-suffixes $(find * -name *.ISO -type f) $(find * -name *.ISO -type f)

      - name: Create release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create -d -t "$GITHUB_WORKFLOW on $(date "+%A, %d of %B of %Y")" $(date "+%y.%m.%d.%H.%M.%S") "./${{ steps.iso.outputs.name }}**"
