name: uYouEnhanced

on:
  workflow_dispatch:
  push:
    paths: .github/workflows/uyouplus.yml
    branches: main

jobs:
  build:
    name: Build uYou
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos
      UYOU_VERSION: 3.0.3
      YOUTUBE_VERSION: 19.10.7
      YOUTUBE_URL: https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.10.7?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwODQxNjMyLCJpYXQiOjE3MTEyODcxODMsImV4cCI6MTcxMTI5Nzk4MywiYXBwaWQiOjU0NDAwNzY2NCwiYXBwdmVyIjoiMTkuMTAuNyJ9.80kge9KW7UDF9Fvm39Kad4k1UDXnw6ml7I8aGIf-Yrg
      BUNDLE_ID: com.google.ios.youtube
      APP_NAME: YouTube
      CREATE_RELEASE_DRAFT: true

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.4
        with:
          path: main
          submodules: recursive
          repository: arichornlover/uYouEnhanced

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.4
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v4.0.2
        with:
          path: theos/sdks/
          key: iOS-16.4-SDK-${{ runner.os }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/arichorn/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.4.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.4
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install

      - name: Prepare YouTube iPA
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT

      - name: VirusTotal Scan
        id: vt_orig
        uses: crazy-max/ghaction-virustotal@v4
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: ./main/YouTube.ipa

      - name: Fix Compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

      - name: VirusTotal Scan
        id: vt
        uses: crazy-max/ghaction-virustotal@v4
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: uYouEnhanced_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          repository: theoware/Altstore
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          body: |
            ${{ steps.vt.outputs.analysis }}
            ${{ steps.vt_orig.outputs.analysis }}
