name: Build and Release YTLitePlus

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/uyouplus.yml

jobs:
  build:
    name: Build YTLitePlus
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos
      YTLITEPLUS_VERSION: 2.2
      YOUTUBE_VERSION: 18.34.5
      YOUTUBE_URL: https://und3fy-my.sharepoint.com/personal/2decrypt_und3fy_onmicrosoft_com/_layouts/15/download.aspx?share=EYJ_frt4fM9LgEKdfYmhSRsBL2-d1gWBt0g2I5R_sXEHGQ
      BUNDLE_ID: com.google.ios.youtube
      APP_NAME: YouTube
      CREATE_RELEASE_DRAFT: true

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.0.0
        with:
          path: main
          submodules: recursive
          repository: Balackburn/YTLitePlus

      - name: Set up Rclone
        uses: AnimMouse/setup-rclone@v1.5.1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v2
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v3.3.1
        env:
          cache-name: iOS-16.2-SDK
        with:
          path: theos/sdks/
          key: iOS-16.2-SDK-${{ runner.os }}

      - name: Download iOS 16.2 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/arichorn/sdks/trunk/iPhoneOS16.2.sdk
          mv *.sdk $THEOS/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.0.0
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install

      - name: Prepare YouTube iPA
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          echo -e "==> \033[1mYouTube v${YOUTUBE_VERSION} downloaded! \033[0m"
          unzip -q main/YouTube.ipa -d main/tmp
          rm -rf main/tmp/Payload/YouTube.app/_CodeSignature/CodeResources
          rm -rf main/tmp/Payload/YouTube.app/PlugIns/*
          cp -R main/Extensions/*.appex main/tmp/Payload/YouTube.app/PlugIns
          echo -e "==> \033[1mYouTube v${{ env.YOUTUBE_VERSION }} unpacked! \033[0m"

      - name: VirusTotal Scan
        id: vt_orig
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: ./main/YouTube.ipa

      - name: Fix Compiling & Build Package
        id: build_package
        run: |
          echo "PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\"" >> $HOME/.zprofile
          cd ${{ github.workspace }}/main
          sed -i '' "12s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "11s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile
          sed -i '' "s/^PACKAGE_VERSION.*$/PACKAGE_VERSION = ${{ env.YOUTUBE_VERSION }}-${{ env.YTLITEPLUS_VERSION }}/" Makefile
          make package FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/YTLitePlus_${{ env.YOUTUBE_VERSION }}_${{ env.YTLITEPLUS_VERSION }}.ipa")        
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

      - name: VirusTotal Scan
        id: vt
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: YTLitePlus_${{ env.YOUTUBE_VERSION }}_${{ env.YTLITEPLUS_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
      
      - name: Prepare Release Notes
        run: |
          export TODAY=$(date '+%Y-%m-%d')
          sed "s/%ytliteplus_version%/${{ env.YTLITEPLUS_VERSION }}/g; s/%youtube_version%/${{ env.YOUTUBE_VERSION }}/g; s/%date%/$TODAY/g" \
          main/.github/RELEASE_TEMPLATE/Release.md > ${{ github.workspace }}/release_notes.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          repository: theoware/Altstore
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.YTLITEPLUS_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.YTLITEPLUS_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          body: |
            ${{ steps.vt.outputs.analysis }}
            ${{ steps.vt_orig.outputs.analysis }}
