# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/CercubePlus/blob/main/.github/workflows/Build.yml

name: uYouPlus

on:
  workflow_dispatch:

  push:
    paths: .github/workflows/uyouplus.yml

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos
      UYOU_VERSION: 3.0.1
      YOUTUBE_VERSION: 18.32.2
      YOUTUBE_URL: https://und3fy-my.sharepoint.com/personal/1decrypt_und3fy_onmicrosoft_com/_layouts/15/download.aspx?share=EfErGMAhJyRAhw37c--o8CABDHghxsATQamJhjIk_feMDA
      BUNDLE_ID: com.google.ios.youtube
      APP_NAME: YouTube

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.0.0
        with:
          path: main
          repository: arichorn/uYouPlusExtra
          submodules: recursive

      - name: Set up Rclone
        uses: AnimMouse/setup-rclone@v1.5.1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.0.0
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: theos
          submodules: recursive
      
      - name: Caching
        id: SDK
        uses: actions/cache@v3.3.1
        env:
          cache-name: iOS-16.2-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      
      - name: Download iOS 16.2 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS16.2.sdk
          mv *.sdk $THEOS/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.0.0
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install

      - name: Caching
        id: IPA
        uses: actions/cache@v3.3.1
        env:
          cache-name: $YOUTUBE_SHA256
        with:
          path: main/YouTube.ipa
          key: ${{ env.cache-name }}

      - name: Download YouTube iPA
        if: steps.IPA.outputs.cache-hit != 'true'
        run: |
          wget "$YOUTUBE_URL" -O main/YouTube.ipa && echo -e "==> \033[1mYouTube v$YOUTUBE_VERSION downloaded! \033[0m"

      - name: VirusTotal Scan
        id: vt_orig
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: |
            ./main/YouTube.ipa

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          git submodule update --recursive 
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
          make package IPA=YouTube.ipa FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/uYouPlus_${{ env.YOUTUBE_VERSION  }}_${{ env.UYOU_VERSION }}.ipa")
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

      - name: VirusTotal Scan
        id: vt
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          request_rate: 4
          files: |
            ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: uYouPlus_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - run: rclone copyto ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }} d:YouTube.ipa

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          repository: theoware/Altstore
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          body: |
            ${{ steps.vt.outputs.analysis }}
            ${{ steps.vt_orig.outputs.analysis }}

      - uses: sgpublic/delete-release-action@v1.1
        with:
          repo: theoware/Altstore
          release-drop: true
          release-keep-count: 2
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
          draft-drop-count: -1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
