# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/CercubePlus/blob/main/.github/workflows/Build.yml

name: Build and Release uYouPlus

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of uYou"
        default: "3.0"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        default: "https://und3fy-my.sharepoint.com/personal/1decrypt_und3fy_onmicrosoft_com/_layouts/15/download.aspx?share=ESqf-t3PpotChGNMOO2aDuEBgoRC40mHOPdk3oVyasPn2g"
        required: true
        type: string
      youtube_version:
        description: "The version of YouTube"
        default: "18.29.1"
        required: true
        type: string
      youtube_sha256:
        description: "The sha256 of YouTube"
        default: "165b0c8bb387d947444bc69e81979aa01b2e8a49a4335c01a2436f6bfe50544c"
        required: true
        type: string
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-11
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos
      UYOU_VERSION: ${{ inputs.uyou_version }}
      YOUTUBE_VERSION: ${{ inputs.youtube_version }}
      YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}
      BUNDLE_ID: com.google.ios.youtube
      APP_NAME: YouTube
      YOUTUBE_SHA256: ${{ inputs.youtube_sha256 }}

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3.2.0
        with:
          path: main
          repository: qnblackcat/uYouPlus
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v3.2.0
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
      
      - name: Caching
        id: SDK
        uses: actions/cache@v3.2.0
        env:
          cache-name: iOS-15.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      
      - name: Download iOS 15.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS15.5.sdk
          mv *.sdk $THEOS/sdks

      - name: Setup Theos Jailed
        uses: actions/checkout@v3.2.0
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install

      - name: Caching
        id: IPA
        uses: actions/cache@v3.2.0
        env:
          cache-name: ${{ inputs.youtube_sha256 }}
        with:
          path: main/YouTube.ipa
          key: ${{ env.cache-name }}

      - name: Download YouTube iPA
        if: steps.IPA.outputs.cache-hit != 'true'
        run: |
          wget "$YOUTUBE_URL" -O main/YouTube.ipa && echo -e "==> \033[1mYouTube v${{ inputs.youtube_version }} downloaded! \033[0m"

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./main/YouTube.ipa

      - name: Checksum the YouTube iPA
        run: |
          actual=$(shasum -a 256 "main/YouTube.ipa" | awk '{print $1}')
          echo $actual
          if [ "$actual" = "$YOUTUBE_SHA256" ]; then
              echo "Checksums match. The file is authentic."
          else
              echo "Checksums do not match. The file may have been tampered with or is different."
              exit 1
          fi

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile          
          make package IPA=YouTube.ipa FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/uYouPlus_${{ env.YOUTUBE_VERSION  }}_${{ env.UYOU_VERSION }}.ipa")
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: uYouPlus_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: 1
