name: Ventoy

on:
  push:
    paths: .github/workflows/ventoy.yml
    branches: main
  
  workflow_dispatch:
    inputs: 
      ref:
        description: 'Ref to checkout'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: centos:7
    steps:

    - uses: actions/checkout@v4.2.2
      with:
        repository: ventoy/Ventoy
        ref: ${{ inputs.ref }} 

    - name: Install dependencies
      run: |
        yum provides "*/aarch64-linux-gnu-gcc"
        yum provides "*/mips-linux-gnu-gcc"
        yum -y -q install \
        libXpm net-tools bzip2 wget vim gcc gcc-c++ samba dos2unix glibc-devel glibc.i686 glibc-devel.i686 \
        mpfr.i686 mpfr-devel.i686 rsync autogen autoconf automake libtool gettext* bison binutils \
        flex device-mapper-devel SDL libpciaccess libusb freetype freetype-devel gnu-free-* qemu-* virt-* \
        libvirt* vte* NetworkManager-bluetooth brlapi fuse-devel dejavu* gnu-efi* pesign shim musl-gcc \
        iscsi-initiator-utils grub2-tools zip nasm acpica-tools glibc-static zlib-static xorriso lz4 squashfs-tools \
        gcc-mips-linux-gnu gcc-aarch64-linux-gnu

    - name: Get Ventoy Toolchain
      run: |
        wget -q -P DOC/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/dietlibc-0.34.tar.xz
        wget -q -P DOC/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/musl-1.2.1.tar.gz
        wget -q -P GRUB2/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/grub-2.04.tar.xz
        wget -q -O EDK2/edk2-edk2-stable201911.zip https://codeload.github.com/tianocore/edk2/zip/edk2-stable201911
        wget -q -P /opt/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
        wget -q -P /opt/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/aarch64--uclibc--stable-2020.08-1.tar.bz2
        wget -q -P /opt/ https://github.com/ventoy/vtoytoolchain/releases/download/1.0/mips-loongson-gcc7.3-2019.06-29-linux-gnu.tar.gz

    - name: All in one
      env:
        VTOY_PATH: ${{ github.workspace }}
      run: |
        cd $VTOY_PATH/DOC
        sh prepare_env.sh

        export PATH=$PATH:/opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin:/opt/aarch64--uclibc--stable-2020.08-1/bin:/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/:/opt/mips64el-linux-musl-gcc730/bin/

        cd $VTOY_PATH/GRUB2
        sh buildgrub.sh || exit 1

        cd $VTOY_PATH/IPXE
        sh buildipxe.sh || exit 1

        cd $VTOY_PATH/EDK2
        sh buildedk.sh || exit 1

    - name: Package
      working-directory: INSTALL
      run: sh ventoy_pack.sh CI || exit 1

    - name: Extract for upload
      working-directory: INSTALL
      run: |
        mkdir ventoy-linux
        tar -xf ventoy-*linux* -C ventoy-linux
        mkdir ventoy-windows
        unzip ventoy-*windows* -d ventoy-windows

    - uses: actions/upload-artifact@v4.6.1
      with:
        name: ventoy-windows
        path: INSTALL/ventoy-windows/

    - uses: actions/upload-artifact@v4.6.1
      with:
        name: ventoy-linux
        path: INSTALL/ventoy-linux/

    - uses: actions/upload-artifact@v4.6.1
      with:
        name: ventoy-livecd
        path: INSTALL/ventoy-*livecd*

    - uses: actions/upload-artifact@v4.6.1
      with:
        name: SHA256SUM
        path: INSTALL/sha256.txt
