name: Ventoy

on:
  push:
    paths: .github/workflows/ventoy.yml
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.4.2

    - name: Run docker-compose up
      run: docker-compose up

    - uses: actions/upload-artifact@v2
      with:
        name: ventoy-windows
        path: INSTALL/ventoy-*windows*

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: ventoy-linux
        path: INSTALL/ventoy-*linux*

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: ventoy-livecd
        path: INSTALL/ventoy-*livecd*

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: SHA256SUM
        path: INSTALL/sha256.txt

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: xxx-build-log
        path: DOC/build.log
