name: WSL

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
      - name: Change default version to 2
        run: wsl --set-default-version 2
      - name: Update Packages
        run: |
          wsl -d Ubuntu sudo apt update
          wsl -d Ubuntu sudo apt upgrade
          wsl -d Ubuntu sudo apt autoremove
      - name: Export
        run: wsl --export Ubuntu ubuntu.tar
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: Ubuntu
          path: |
            ubuntu.tar
          if-no-files-found: error
